package knowledge_cat

// Spec is the full text of the Open Knowledge Format (OKF) v0.1 specification.
const Spec = `# Open Knowledge Format (OKF)

**Version 0.1 — Draft**

OKF is an open, human- and agent-friendly format for representing
*knowledge* — the metadata, context, and curated insight that surrounds
data and systems. It is designed to be authored by people, generated by
agents, exchanged across organizations, and consumed by both.

The format is intentionally minimal: a directory of markdown files with
YAML frontmatter. There is no schema registry, no central authority, and
no required tooling. If you can ` + "`cat`" + ` a file, you can read OKF; if you
can ` + "`git clone`" + ` a repo, you can ship it.

---

## 1. Motivation

The space of knowledge representation for AI agents is evolving quickly,
and many incompatible conventions are emerging. OKF takes the position
that knowledge is best represented in commonly accessible, established
formats that are:

- **Readable** by humans without tooling.
- **Parseable** by agents without bespoke SDKs.
- **Diffable** in version control.
- **Portable** across tools, organizations, and time.

### Goals

1. Define a universal format that **enrichment agents** can write into.
2. Inform how **consumption agents** should read and traverse it.
3. Facilitate **exchange** of knowledge across systems and organizations.
4. Standardize the small number of **required** fields that must be
   present for content to be meaningfully consumed.

---

## 2. Terminology

- **Knowledge Bundle** — A self-contained, hierarchical collection of
  knowledge documents. The unit of distribution.
- **Concept** — A single unit of knowledge within a bundle. Represented
  as one markdown document. May describe a tangible asset (a table, an
  API), an abstract idea (a metric, a business process), or anything in
  between.
- **Concept ID** — The path of the concept's file within the bundle,
  with the ` + "`.md`" + ` suffix removed.
- **Frontmatter** — YAML metadata block delimited by ` + "`---`" + ` at the top of
  a markdown file.
- **Body** — Everything in the file after the frontmatter.
- **Link** — A standard markdown link from one concept to another.
- **Citation** — A link from a concept to an external source.

---

## 3. Bundle Structure

A bundle is a directory tree of markdown files. The directory structure
is independent of the domain.

` + "```" + `
path/to/bundle/
├── index.md                      # Directory listing (§6)
├── log.md                        # Update history (§7)
├── <concept>.md                  # A concept at the bundle root.
└── <subdirectory>/
    ├── index.md
    ├── <concept>.md
    └── …
` + "```" + `

### 3.1 Reserved filenames

| Filename   | Purpose          |
|------------|------------------|
| index.md   | Directory listing (§6) |
| log.md     | Update history (§7)   |

---

## 4. Concept Documents

Every concept is a UTF-8 markdown file:

1. A **YAML frontmatter block**, delimited by ` + "`---`" + `.
2. A **markdown body**, containing free-form content.

### 4.1 Frontmatter

` + "```yaml" + `
---
type: <Type name>                  # REQUIRED
title: <Optional display name>
description: <Optional one-line summary>
resource: <Optional canonical URI>
tags: [<tag>, …]                   # Optional
timestamp: <ISO 8601 datetime>     # Optional
---
` + "```" + `

**Required:** ` + "`type`" + ` — short string identifying the kind of concept.

**Recommended:** ` + "`title`" + `, ` + "`description`" + `, ` + "`resource`" + `, ` + "`tags`" + `, ` + "`timestamp`" + `.

### 4.2 Body

Standard markdown. Conventional section headings:
- ` + "`# Schema`" + ` — structured field/column descriptions
- ` + "`# Examples`" + ` — concrete usage examples
- ` + "`# Citations`" + ` — external sources (§8)

---

## 5. Cross-linking

Concepts MAY link to other concepts using standard markdown links.

### 5.1 Absolute (bundle-relative) links
Begin with ` + "`/`" + `, interpreted relative to the bundle root.
` + "```markdown" + `
See [customers table](/tables/customers.md) for the join key.
` + "```" + `

### 5.2 Relative links
Standard markdown relative paths.
` + "```markdown" + `
See [neighboring concept](./other.md).
` + "```" + `

---

## 6. Index Files

` + "`index.md`" + ` files enumerate a directory's contents for progressive disclosure.
No frontmatter. Body uses sections grouping concepts:

` + "```markdown" + `
# Section Heading
* [Title 1](url-1) - description
* [Title 2](url-2) - description
` + "```" + `

---

## 7. Log Files (optional)

` + "`log.md`" + ` records chronological history, newest first:

` + "```markdown" + `
# Directory Update Log

## 2026-05-22
* **Update**: Added [Customer Metrics](/tables/customer-metrics.md).
* **Creation**: Established [Dataplex Playbook](/playbooks/dataplex.md).
` + "```" + `

---

## 8. Citations

Listed under ` + "`# Citations`" + ` heading, numbered:

` + "```markdown" + `
# Citations
[1] [Source title](https://example.com/...)
[2] [Another source](https://example.com/...)
` + "```" + `

---

## 9. Conformance

A bundle is **conformant** with OKF v0.1 if:
1. Every non-reserved ` + "`.md`" + ` file has parseable YAML frontmatter.
2. Every frontmatter block has a non-empty ` + "`type`" + ` field.
3. Reserved filenames follow §6 and §7 when present.

Consumers MUST tolerate missing optional fields, unknown types, broken
links, and missing index files.

---

## 10. Versioning

OKF version **0.1**. Bundles MAY declare ` + "`okf_version: \"0.1\"`" + ` in
a bundle-root ` + "`index.md`" + ` frontmatter block.

Full spec: https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md
`
